on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Feel free to close
      uses: actions/github-script@v6
      with:
        script: |
          console.log(context.payload);
          const body =
            (context.eventName === "issue_comment"
            // For comments on pull requests
                ? context.payload.comment.body
                // For the initial pull request description
                : context.payload.pull_request.body) || '';
          if (!body.match(/\bfeel\s+free\s+to\s+close\b/i)) {
            return;
          }
    
          github.rest.issues.update({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed',
          })

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Thank you for your contributions. 'Feel free to close' action has detected that you have indicated that this issue can be closed, and has closed the issue upon your request.\n\nIf this was a mistake, please re-open the issue and continue your discussion.\n\nPlease remember to be responsible for issues that you have raised, and close them yourself if you no longer want to work on it."
          })
    
